FROM python:3.10

# Set work directory
WORKDIR /app

# Install dependencies
COPY outreach_backend/requirements.txt .

RUN pip install --upgrade pip
RUN pip install -r requirements.txt

# Copy project
COPY . .

# Set environment variable
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# Run gunicorn
CMD ["gunicorn", "outreach_backend.wsgi:application", "--bind", "0.0.0.0:8000"]
